<GrenciadorTelas>:
    Menu:
        name: 'menu'

    Tarefas:
        name: 'tarefas'

<Menu>:
    BoxLayout:
        orientation: 'vertical'
        padding: "200dp"
        spacing: "20dp"
        canvas.before:
            Color:
                rgba:(.2, .2, .2, 1)
            Rectangle:
                pos: self.pos
                size: self.size
        Image:
            source: 'Image/logo.png'
            size_hint_y: None
            height: "200dp"
            allow_stretch: True

        BotaoCustomizado:
            text: 'Tarefas'
            on_release:
                root.manager.transition.direction = 'left'
                app.root.current = 'tarefas'
            size_hint_y: None
            height: "40dp"

        BotaoCustomizado:
            text: 'Assistente'
            size_hint_y: None
            height: "40dp"

        BotaoCustomizado:
            text: 'Sair'
            size_hint_y: None
            height: "40dp"
            on_release: root.confirmacao()



<Tarefas>:
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba:(.2, .2, .2, 1)
            Rectangle:
                pos: self.pos
                size: self.size
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'Tarefas'
                    on_release:
                        root.manager.transition.direction = 'right'
                        app.root.current = 'menu'

                ActionButton:
                    text: 'Sair'
                    on_release: app.root.get_screen('menu').confirmacao()
        ScrollView:
            BoxLayout:
                id:box
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height

        BoxLayout:
            size_hint_y: None
            height: "50dp"
            TextInput:
                id:texto
                multiline:False

            Button:
                text: 'Add'
                size_hint_x: None
                width: "60dp"
                on_release:root.add_widget_tarefas()

<Tarefa>:
    size_hint_y: None
    height:"100dp"
    Label:
        id:label
        font_size: "30dp"
    Button:
        text: 'X'
        size_hint_x: None
        width: "60dp"
        on_release: app.root.get_screen('tarefas').removeWidget(root)
