<GrenciadorTelas>:
    Menu:
        name: 'menu'

    Tarefas:
        name: 'tarefas'

<Menu>:
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba:(.2, .2, .2, 1)
            Rectangle:
                pos: self.pos
                size: self.size
        padding: 200
        spacing: 20
        Image:
            source: 'Image/logo.png'
            size_hint_y: None
            height: 200
            allow_stretch: True

        Button:
            text: 'Tarefas'
            on_release:
                root.manager.transition.direction = 'left'
                app.root.current = 'tarefas'
            size_hint_y: None
            height: 40

        Button:
            text: 'Assistente'
            size_hint_y: None
            height: 40

        Button:
            text: 'Sair'
            size_hint_y: None
            height: 40
            on_release: app.stop()

<Tarefas>:
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba:(.2, .2, .2, 1)
            Rectangle:
                pos: self.pos
                size: self.size
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'Tarefas'
                    on_release:
                        root.manager.transition.direction = 'right'
                        app.root.current = 'menu'

                ActionButton:
                    text: 'Sair'
                    on_release: app.stop()
        ScrollView:
            BoxLayout:
                id:box
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height

        BoxLayout:
            size_hint_y: None
            height: 50
            TextInput:
                id:texto
                multiline:False

            Button:
                text: 'Add'
                size_hint_x: None
                width: 60
                on_release:root.add_widget_tarefas()

<Tarefa>:
    size_hint_y: None
    height:100
    Label:
        id:label
        font_size: 30
    Button:
        text: 'X'
        size_hint_x: None
        width: 60
        on_release: app.root.get_screen('tarefas').ids.box.remove_widget(root)
